server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/brtacer/bankofconfig.git"
          default-label: main
          skip-ssl-validation: true
          username: brtacer
          password: ${BANK_OF_CONFIG}